APOCLootPrioData = {
  ["Serpentshrine Cavern"] = {
    {
      boss = "Hydross the Unstable",
      items = {
        {name = "Living Root of the Wildheart", id = 30664, bias = "MS > OS"},
        {name = "Scarab of Displacement", id = 30629, bias = "MS > OS"},
        {name = "Band of Vile Aggression", id = 33055, bias = "MS > OS"},
        {name = "Ring of Lethality", id = 30052, bias = "Rogue = Hunter = Enhance = Cat"},
        {name = "Robe of Hateful Echoes", id = 30056, bias = "MS > OS"},
        {name = "Boots of the Shifting Nightmare", id = 30050, bias = "Shadow = Demo"},
        {name = "Wraps of Purification", id = 32516, bias = "MS > OS"},
        {name = "Shoulderpads of the Stranger", id = 30055, bias = "Ret > Melee"},
        {name = "Ranger-General's Chestguard", id = 30054, bias = "MS > OS"},
        {name = "Blackfathom Warbands", id = 30047, bias = "Holy = Resto"},
        {name = "Brighthelm of Justice", id = 30048, bias = "MS > OS"},
        {name = "Pauldrons of the Wardancer", id = 30053, bias = "MS > OS"},
        {name = "Fathomstone", id = 30049, bias = "Warlock = Balance"},
      },
    },
    {
      boss = "The Lurker Below",
      items = {
        {name = "Earring of Soulful Meditation", id = 30665, bias = "MS > OS"},
        {name = "The Seal of Danzalar", id = 33054, bias = "MS > OS"},
        {name = "Ancestral Ring of Conquest", id = 30061, bias = "MS > OS"},
        {name = "Choker of Animalistic Fury", id = 30059, bias = "MS > OS"},
        {name = "Velvet Boots of the Guardian", id = 30067, bias = "Mage = Ele = Balance"},
        {name = "Cord of Screaming Terrors", id = 30064, bias = "MS > OS"},
        {name = "Boots of Effortless Striking", id = 30060, bias = "MS > OS"},
        {name = "Grove-Bands of Remulos", id = 30062, bias = "Resto"},
        {name = "Tempest-Strider Boots", id = 30066, bias = "MS > OS"},
        {name = "Glowing Breastplate of Truth", id = 30065, bias = "MS > OS"},
        {name = "Bracers of Eradication", id = 30057, bias = "MS > OS"},
        {name = "Mallet of the Tides", id = 30058, bias = "Prot"},
      },
    },
    {
      boss = "Leotheras the Blind",
      items = {
        {name = "Gloves of the Vanquished Champion", id = 30239, bias = "MS > OS"},
        {name = "Gloves of the Vanquished Defender", id = 30240, bias = "MS > OS"},
        {name = "Gloves of the Vanquished Hero", id = 30241, bias = "MS > OS"},
        {name = "Tsunami Talisman", id = 30627, bias = "MS > OS"},
        {name = "Orca-Hide Boots", id = 30092, bias = "MS > OS"},
        {name = "Grove-Bands of Remulos", id = 30062, bias = "Resto"},
        {name = "Coral-Barbed Shoulderpads", id = 30097, bias = "MS > OS"},
        {name = "True-Aim Stalker Bands", id = 30091, bias = "MS > OS"},
        {name = "Girdle of the Invulnerable", id = 30096, bias = "MS > OS"},
        {name = "Fang of the Leviathan", id = 30095, bias = "MS > OS"},
      },
    },
    {
      boss = "Fathom-Lord Karathress",
      items = {
        {name = "Leggings of the Vanquished Champion", id = 30245, bias = "Prot = Rogue = Enhance = Ele"},
        {name = "Leggings of the Vanquished Defender", id = 30246, bias = "MS > OS"},
        {name = "Leggings of the Vanquished Hero", id = 30247, bias = "MS > OS"},
        {name = "Fathom-Brooch of the Tidewalker", id = 30663, bias = "MS > OS"},
        {name = "Sextant of Unstable Currents", id = 30626, bias = "Fire"},
        {name = "Frayed Tether of the Drowned", id = 30099, bias = "MS > OS"},
        {name = "Soul-Strider Boots", id = 30100, bias = "Holy"},
        {name = "Bloodsea Brigand's Vest", id = 30101, bias = "Cat = Rogue = Warrior"},
        {name = "World Breaker", id = 30090, bias = "MS > OS"},
      },
    },
    {
      boss = "Morogrim Tidewalker",
      items = {
        {name = "Serpent-Coil Braid", id = 30720, bias = "MS > OS"},
        {name = "Band of the Vigilant", id = 33058, bias = "MS > OS"},
        {name = "Ring of Sundered Souls", id = 30083, bias = "MS > OS"},
        {name = "Pendant of the Lost Ages", id = 30008, bias = "MS > OS"},
        {name = "Razor-Scale Battlecloak", id = 30098, bias = "MS > OS"},
        {name = "Illidari Shoulderpads", id = 30079, bias = "MS > OS"},
        {name = "Gnarled Chestpiece of the Ancients", id = 30075, bias = "MS > OS"},
        {name = "Mantle of the Tireless Tracker", id = 30085, bias = "MS > OS"},
        {name = "Girdle of the Tidal Call", id = 30068, bias = "MS > OS"},
        {name = "Warboots of Obliteration", id = 30081, bias = "MS > OS"},
        {name = "Pauldrons of the Argent Sentinel", id = 30084, bias = "MS > OS"},
        {name = "Talon of Azshara", id = 30082, bias = "MS > OS"},
        {name = "Luminescent Rod of the Naaru", id = 30080, bias = "MS > OS"},
      },
    },
    {
      boss = "Lady Vashj",
      items = {
        {name = "Helm of the Vanquished Champion", id = 30242, bias = "MS > OS"},
        {name = "Helm of the Vanquished Defender", id = 30243, bias = "MS > OS"},
        {name = "Helm of the Vanquished Hero", id = 30244, bias = "MS > OS"},
        {name = "Prism of Inner Calm", id = 30621, bias = "MS > OS"},
        {name = "Coral Band of the Revived", id = 30110, bias = "MS > OS"},
        {name = "Ring of Endless Coils", id = 30109, bias = "Warlock = Shadow = Ele = Balance"},
        {name = "Vestments of the Sea-Witch", id = 30107, bias = "Warlock = Fire > Ele"},
        {name = "Runetotem's Mantle", id = 30111, bias = "Resto"},
        {name = "Belt of One-Hundred Deaths", id = 30106, bias = "Bear > Melee DPS"},
        {name = "Cobra-Lash Boots", id = 30104, bias = "Hunter"},
        {name = "Krakken-Heart Breastplate", id = 30102, bias = "MS > OS"},
        {name = "Glorious Gauntlets of Crestfall", id = 30112, bias = "MS > OS"},
        {name = "Fang of Vashj", id = 30103, bias = "MS > OS"},
        {name = "Lightfathom Scepter", id = 30108, bias = "MS > OS"},
        {name = "Serpent Spine Longbow", id = 30105, bias = "Hunter"},
        {name = "Nether Vortex", id = 30183, bias = "Crafting"},
      },
    },
    {
      boss = "Trash",
      items = {
        {name = "Spyglass of the Hidden Fleet", id = 30620, bias = "MS > OS"},
        {name = "Pendant of the Perilous", id = 30022, bias = "MS > OS"},
        {name = "Totem of the Maelstrom", id = 30023, bias = "MS > OS"},
        {name = "Boots of Courage Unending", id = 30027, bias = "MS > OS"},
        {name = "Wildfury Greatstaff", id = 30021, bias = "MS > OS"},
        {name = "Serpentshrine Shuriken", id = 30025, bias = "MS > OS"},
      },
    },
  },

  ["The Eye"] = {
    {
      boss = "Al'ar",
      items = {
        {name = "Band of Al'ar", id = 29922, bias = "Shadow"},
        {name = "Phoenix-Ring of Rebirth", id = 29920, bias = "MS > OS"},
        {name = "Phoenix-Wing Cloak", id = 29925, bias = "Prot"},
        {name = "Mindstorm Wristbands", id = 29918, bias = "Warlock = Mage = Balance = Ele > Shadow"},
        {name = "Gloves of the Searing Grip", id = 29947, bias = "MS > OS"},
        {name = "Fire Crest Breastplate", id = 29921, bias = "MS > OS"},
        {name = "Netherbane", id = 29924, bias = "MS > OS"},
        {name = "Claw of the Phoenix", id = 29948, bias = "MS > OS"},
        {name = "Talon of the Phoenix", id = 32944, bias = "BM > Enhance"},
        {name = "Arcanite Steam-Pistol", id = 29949, bias = "MS > OS"},
        {name = "Talisman of the Sun King", id = 29923, bias = "MS > OS"},
        {name = "Talon of Al'ar", id = 30448, bias = "MS > OS"},
        {name = "Tome of Fiery Redemption", id = 30447, bias = "MS > OS"},
      },
    },
    {
      boss = "Void Reaver",
      items = {
        {name = "Pauldrons of the Vanquished Champion", id = 30248, bias = "MS > OS"},
        {name = "Pauldrons of the Vanquished Defender", id = 30249, bias = "MS > OS"},
        {name = "Pauldrons of the Vanquished Hero", id = 30250, bias = "Hunter = Arcane"},
        {name = "Cowl of the Grand Engineer", id = 29986, bias = "MS > OS"},
        {name = "Girdle of Zaetar", id = 29984, bias = "Resto Druid"},
        {name = "Void Reaver Greaves", id = 29985, bias = "MS > OS"},
        {name = "Fel-Steel Warhelm", id = 29983, bias = "MS > OS"},
        {name = "Wristguards of Determination", id = 32515, bias = "MS > OS"},
        {name = "Warp-Spring Coil", id = 30450, bias = "MS > OS"},
        {name = "Fel Reaver's Piston", id = 30619, bias = "MS > OS"},
      },
    },
    {
      boss = "High Astromancer Solarian",
      items = {
        {name = "Trousers of the Astromancer", id = 29972, bias = "Shadow"},
        {name = "Star-Soul Breeches", id = 29977, bias = "MS > OS"},
        {name = "Vambraces of Ending", id = 29966, bias = "Rogue = Cat > Hunter"},
        {name = "Star-Strider Boots", id = 29951, bias = "MS > OS"},
        {name = "Worldstorm Gauntlets", id = 29976, bias = "Resto"},
        {name = "Boots of the Resilient", id = 32267, bias = "MS > OS"},
        {name = "Greaves of the Bloodwarder", id = 29950, bias = "MS > OS"},
        {name = "Girdle of the Righteous Path", id = 29965, bias = "MS > OS"},
        {name = "Heartrazor", id = 29962, bias = "MS > OS"},
        {name = "Ethereum Life-Staff", id = 29981, bias = "Resto = Holy"},
        {name = "Wand of the Forgotten Star", id = 29982, bias = "MS > OS"},
        {name = "Solarian's Sapphire", id = 30446, bias = "MS > OS"},
        {name = "Void Star Talisman", id = 30449, bias = "MS > OS"},
      },
    },
    {
      boss = "Kael'thas Sunstrider",
      items = {
        {name = "Ashes of Al'ar", id = 32458, bias = "Mount"},
        {name = "Chestguard of the Vanquished Champion", id = 30236, bias = "MS > OS"},
        {name = "Chestguard of the Vanquished Defender", id = 30237, bias = "MS > OS"},
        {name = "Chestguard of the Vanquished Hero", id = 30238, bias = "MS > OS"},
        {name = "Band of the Ranger-General", id = 29997, bias = "Rogue = DPS = Enhance = BM > Ret"},
        {name = "Sunshower Light Cloak", id = 29989, bias = "MS > OS"},
        {name = "Royal Cloak of the Sunstriders", id = 29992, bias = "Shadow = Demo > Arcane"},
        {name = "Thalassian Wildercloak", id = 29994, bias = "Hunter > Feral > Rogue = Enhance"},
        {name = "Gauntlets of the Sun King", id = 29987, bias = "MS > OS"},
        {name = "Crown of the Sun", id = 29990, bias = "MS > OS"},
        {name = "Leggings of Murderous Intent", id = 29995, bias = "MS > OS"},
        {name = "Sunhawk Leggings", id = 29991, bias = "MS > OS"},
        {name = "Royal Gauntlets of Silvermoon", id = 29998, bias = "MS > OS"},
        {name = "Rod of the Sun King", id = 29996, bias = "MS > OS"},
        {name = "The Nexus Key", id = 29988, bias = "Ele = Mage"},
        {name = "Twinblade of the Phoenix", id = 29993, bias = "MS > OS"},
        {name = "Verdant Sphere", id = 32405, bias = "Nearly all classes; use discretion"},
        {name = "Kael's Vial Remnant", id = 29905, bias = "Attunement"},
      },
    },
    {
      boss = "Trash",
      items = {
        {name = "Seventh Ring of the Tirisfalen", id = 30028, bias = "MS > OS"},
        {name = "Mantle of the Elven Kings", id = 30024, bias = "MS > OS"},
        {name = "Fire-Cord of the Magus", id = 30020, bias = "MS > OS"},
        {name = "Bark-Gloves of Ancient Wisdom", id = 30029, bias = "MS > OS"},
        {name = "Girdle of Fallen Stars", id = 30030, bias = "MS > OS"},
        {name = "Bands of the Celestial Archer", id = 30026, bias = "MS > OS"},
      },
    },
  },

  ["Mount Hyjal"] = {
    {
      boss = "Rage Winterchill",
      items = {
        {name = "Bracers of Martyrdom", id = 30871, bias = "Holy > Resto"},
        {name = "Cuffs of Devastation", id = 30870, bias = "Arcane > Balance"},
        {name = "Deadly Cuffs", id = 30863, bias = "DPS > Enhance"},
        {name = "Rejuvenating Bracers", id = 30868, bias = "Resto"},
        {name = "Bracers of the Pathfinder", id = 30864, bias = "MS > OS"},
        {name = "Howling Wind Bracers", id = 30869, bias = "MS > OS"},
        {name = "Stillwater Boots", id = 30873, bias = "MS > OS"},
        {name = "Blood-Stained Pauldrons", id = 30866, bias = "MS > OS"},
        {name = "Blessed Adamantite Bracers", id = 30862, bias = "Holy"},
        {name = "Furious Shackles", id = 30861, bias = "MS > OS"},
        {name = "Tracker's Blade", id = 30865, bias = "MS > OS"},
        {name = "Chronicle of Dark Secrets", id = 30872, bias = "Warlock = Mage > Balance"},
      },
    },
    {
      boss = "Anetheron",
      items = {
        {name = "Hatefury Mantle", id = 30884, bias = "MS > OS"},
        {name = "Anetheron's Noose", id = 30888, bias = "Arcane > Warlock = Balance"},
        {name = "Archbishop's Slippers", id = 30885, bias = "MS > OS"},
        {name = "Don Alejandro's Money Belt", id = 30879, bias = "Survival > BM > Feral", note = "Check hit!"},
        {name = "Enchanted Leather Sandals", id = 30886, bias = "MS > OS"},
        {name = "Golden Links of Restoration", id = 30887, bias = "MS > OS"},
        {name = "Quickstrider Moccasins", id = 30880, bias = "MS > OS"},
        {name = "Glimmering Steel Mantle", id = 30878, bias = "MS > OS"},
        {name = "The Unbreakable Will", id = 30874, bias = "MS > OS"},
        {name = "Blade of Infamy", id = 30881, bias = "Survival > BM > DPS", note = "Prioritize melee who never got Talon"},
        {name = "Pillar of Ferocity", id = 30883, bias = "Bear > Cat"},
        {name = "Bastion of Light", id = 30882, bias = "Resto > Holy"},
      },
    },
    {
      boss = "Kaz'Rogal",
      items = {
        {name = "Angelista's Sash", id = 30895, bias = "Holy > Resto"},
        {name = "Leggings of Channeled Elements", id = 30916, bias = "Balance > Ele > Shadow"},
        {name = "Blue Suede Shoes", id = 30894, bias = "MS > OS"},
        {name = "Razorfury Mantle", id = 30917, bias = "MS > OS"},
        {name = "Belt of the Crescent Moon", id = 30914, bias = "Balance > Ele"},
        {name = "Black Featherlight Boots", id = 30891, bias = "MS > OS"},
        {name = "Beast-Tamer's Shoulders", id = 30892, bias = "MS > OS"},
        {name = "Valestalker Girdle", id = 30919, bias = "Ret"},
        {name = "Sun-Touched Chain Leggings", id = 30893, bias = "Resto > Holy"},
        {name = "Belt of Seething Fury", id = 30915, bias = "MS > OS"},
        {name = "Hammer of Atonement", id = 30918, bias = "Holy > Resto > Holy > Resto"},
        {name = "Kaz'Rogal's Hardened Heart", id = 30889, bias = "Prot"},
      },
    },
    {
      boss = "Azgalor",
      items = {
        {name = "Don Rodrigo's Poncho", id = 30899, bias = "MS > OS"},
        {name = "Shady Dealer's Pantaloons", id = 30898, bias = "MS > OS"},
        {name = "Bow-Stitched Leggings", id = 30900, bias = "Survival > Ret = Enhance > BM"},
        {name = "Glory of the Defender", id = 30896, bias = "MS > OS"},
        {name = "Girdle of Hope", id = 30897, bias = "Holy"},
        {name = "Boundless Agony", id = 30901, bias = "BM"},
        {name = "Gloves of the Forgotten Conqueror", id = 31092, bias = "Prot > Destro > Holy >= Shadow"},
        {name = "Gloves of the Forgotten Protector", id = 31094, bias = "Ele > Hunter > DPS"},
        {name = "Gloves of the Forgotten Vanquisher", id = 31093, bias = "Bear > Rogue > Cat > Balance"},
      },
    },
    {
      boss = "Archimonde",
      items = {
        {name = "Robes of Rhonin", id = 30913, bias = "MS > OS"},
        {name = "Leggings of Eternity", id = 30912, bias = "Holy > Resto"},
        {name = "Midnight Chestguard", id = 30905, bias = "Enhance > Ret"},
        {name = "Mail of Fevered Pursuit", id = 30907, bias = "MS > OS"},
        {name = "Savior's Grasp", id = 30904, bias = "MS > OS"},
        {name = "Legguards of Endless Rage", id = 30903, bias = "MS > OS"},
        {name = "Scepter of Purification", id = 30911, bias = "Holy > Resto"},
        {name = "Tempest of Chaos", id = 30910, bias = "Prot > Mage = Warlock"},
        {name = "Cataclysm's Edge", id = 30902, bias = "Arms > Ret"},
        {name = "Apostle of Argus", id = 30908, bias = "Resto > Holy > Resto"},
        {name = "Antonidas's Aegis of Rapt Concentration", id = 30909, bias = "Ele > Prot"},
        {name = "Bristleblitz Striker", id = 30906, bias = "BM > Survival"},
        {name = "Helm of the Forgotten Conqueror", id = 31097, bias = "Prot > Warlock > Holy > Holy > Shadow"},
        {name = "Helm of the Forgotten Protector", id = 31095, bias = "Ele = Resto > Survival > Arms > Fury"},
        {name = "Helm of the Forgotten Vanquisher", id = 31096, bias = "Bear > Rogue > Cat > Balance > Resto"},
      },
    },
    {
      boss = "Trash",
      items = {
        {name = "Nethervoid Cloak", id = 32590, bias = "Shadow > Warlock"},
        {name = "Pepe's Shroud of Pacification", id = 34010, bias = "Prot >= Bear = Prot"},
        {name = "Boots of the Divine Light", id = 32609, bias = "Holy >= Resto > Resto = Holy"},
        {name = "Chestguard of Relentless Storms", id = 32592, bias = "MS > OS"},
        {name = "Choker of Serrated Blades", id = 32591, bias = "BM = DPS"},
        {name = "Hellfire-Encased Pendant", id = 32589, bias = "MS > OS"},
        {name = "Hammer of Judgement", id = 34009, bias = "MS > OS"},
        {name = "Claw of Molten Fury", id = 32946, bias = "MS > OS"},
        {name = "Fist of Molten Fury", id = 32945, bias = "MS > OS"},
      },
    },
    {
      boss = "Patterns",
      items = {
        {name = "Dawnsteel Bracers", id = 32571, bias = "MS > OS"},
        {name = "Dawnsteel Shoulders", id = 32573, bias = "MS > OS"},
        {name = "Swiftsteel Bracers", id = 32568, bias = "MS > OS"},
        {name = "Swiftsteel Shoulders", id = 32570, bias = "MS > OS"},
        {name = "Bindings of Lightning Reflexes", id = 32574, bias = "Ret > Enhance > Hunter > DPS"},
        {name = "Bracers of Renewed Life", id = 32582, bias = "Resto"},
        {name = "Living Earth Bindings", id = 32577, bias = "Resto"},
        {name = "Living Earth Shoulders", id = 32579, bias = "MS > OS"},
        {name = "Shoulders of Lightning Reflexes", id = 32575, bias = "MS > OS"},
        {name = "Shoulderpads of Renewed Life", id = 32583, bias = "Resto"},
        {name = "Swiftstrike Bracers", id = 32580, bias = "MS > OS"},
        {name = "Swiftstrike Shoulders", id = 32581, bias = "Enhance > Ret > Hunter > DPS"},
        {name = "Bracers of Nimble Thought", id = 32586, bias = "Shadow > Destro = Ele > Balance > Arcane"},
        {name = "Mantle of Nimble Thought", id = 32587, bias = "MS > OS"},
        {name = "Swiftheal Mantle", id = 32585, bias = "Resto > Holy", note = "If Tailoring"},
        {name = "Swiftheal Wraps", id = 32584, bias = "Resto > Holy"},
      },
    },
  },

  ["Black Temple"] = {
    {
      boss = "High Warlord Naj'entus",
      items = {
        {name = "Slippers of the Seacaller", id = 32239, bias = "Mage > Warlock > Balance > Ele"},
        {name = "Guise of the Tidal Lurker", id = 32240, bias = "MS > OS"},
        {name = "Mantle of Darkness", id = 32377, bias = "MS > OS"},
        {name = "Helm of Soothing Currents", id = 32241, bias = "MS > OS"},
        {name = "Fists of Mukoa", id = 32234, bias = "Enhance > MS > OS"},
        {name = "Boots of Oceanic Fury", id = 32242, bias = "Ele"},
        {name = "Eternium Shell Bracers", id = 32232, bias = "MS > OS"},
        {name = "Pearl Inlaid Boots", id = 32243, bias = "Holy"},
        {name = "Tide-stomper's Greaves", id = 32245, bias = "Prot"},
        {name = "Ring of Calming Waves", id = 32238, bias = "Holy > Resto"},
        {name = "Ring of Captured Storms", id = 32247, bias = "MS > OS"},
        {name = "The Maelstrom's Fury", id = 32237, bias = "Ele = Balance > Shadow"},
        {name = "Rising Tide", id = 32236, bias = "Fury Orc > Enhance"},
        {name = "Halberd of Desolation", id = 32248, bias = "Hunter"},
      },
    },
    {
      boss = "Supremus",
      items = {
        {name = "Waistwrap of Infinity", id = 32256, bias = "Shadow > Warlock > Balance > Mage"},
        {name = "Nether Shadow Tunic", id = 32252, bias = "Enhance"},
        {name = "Bands of the Coming Storm", id = 32259, bias = "Ele"},
        {name = "Wraps of Precise Flight", id = 32251, bias = "MS > OS"},
        {name = "Naturalist's Preserving Cinch", id = 32258, bias = "Resto > Holy"},
        {name = "Pauldrons of Abyssal Fury", id = 32250, bias = "MS > OS"},
        {name = "Choker of Endless Nightmares", id = 32260, bias = "Enhance = Rogue > Ret > BM = DPS > Cat", note = "BiS for Feral without a Boomkin"},
        {name = "Band of the Abyssal Lord", id = 32261, bias = "Prot = Bear"},
        {name = "Idol of the White Stag", id = 32257, bias = "MS > OS"},
        {name = "The Brutalizer", id = 32254, bias = "Prot"},
        {name = "Syphon of the Nathrezim", id = 32262, bias = "Enhance > DPS > Rogue"},
        {name = "Felstone Bulwark", id = 32255, bias = "Holy > Resto"},
        {name = "Legionkiller", id = 32253, bias = "Hunter > Prot"},
      },
    },
    {
      boss = "Shade of Akama",
      items = {
        {name = "Amice of Brilliant Light", id = 32273, bias = "MS > OS"},
        {name = "Focused Mana Bindings", id = 32270, bias = "MS > OS"},
        {name = "Wristbands of Divine Influence", id = 32513, bias = "MS > OS"},
        {name = "Shadow-walker's Cord", id = 32265, bias = "Ret"},
        {name = "Kilt of Immortal Nature", id = 32271, bias = "Resto > Resto = Holy"},
        {name = "Shoulders of the Hidden Predator", id = 32264, bias = "MS > OS"},
        {name = "Spiritwalker Gauntlets", id = 32275, bias = "Resto > Holy"},
        {name = "Flashfire Girdle", id = 32276, bias = "Ele"},
        {name = "The Seeker's Wristguards", id = 32279, bias = "Prot"},
        {name = "Grips of Silent Justice", id = 32278, bias = "Fury > Arms"},
        {name = "Praetorian's Legguards", id = 32263, bias = "Prot"},
        {name = "Myrmidon's Treads", id = 32268, bias = "Prot"},
        {name = "Ring of Deceitful Intent", id = 32266, bias = "Bear > Hunter > Rogue > Enhance"},
        {name = "Blind-Seers Icon", id = 32361, bias = "MS > OS"},
      },
    },
    {
      boss = "Gurtogg Bloodboil",
      items = {
        {name = "Shroud of Forgiveness", id = 32337, bias = "No Sunshower > Resto > Holy"},
        {name = "Blood-cursed Shoulderpads", id = 32338, bias = "MS > OS"},
        {name = "Garments of Temperance", id = 32340, bias = "MS > OS"},
        {name = "Belt of Primal Majesty", id = 32339, bias = "Resto > Resto > Holy"},
        {name = "Vest of Mounting Assault", id = 32334, bias = "MS > OS"},
        {name = "Girdle of Mighty Resolve", id = 32342, bias = "Prot"},
        {name = "Girdle of Stability", id = 32333, bias = "Prot"},
        {name = "Leggings of Divine Retribution", id = 32341, bias = "DPS"},
        {name = "Unstoppable Aggressor's Ring", id = 32335, bias = "DPS > Cat"},
        {name = "Shadowmoon Insignia", id = 32501, bias = "Bear > Prot > Prot"},
        {name = "Messenger of Fate", id = 32269, bias = "MS > OS"},
        {name = "Staff of Immaculate Recovery", id = 32344, bias = "MS > OS"},
        {name = "Wand of Prismatic Focus", id = 32343, bias = "Shadow > Warlock > Arcane"},
      },
    },
    {
      boss = "Reliquary of the Lost",
      items = {
        {name = "Gloves of Unfailing Faith", id = 32353, bias = "MS > OS"},
        {name = "Elunite Empowered Bracers", id = 32351, bias = "Balance"},
        {name = "Grips of Damnation", id = 32347, bias = "Enhance > MS > OS"},
        {name = "Naturewarden's Treads", id = 32352, bias = "Balance = Ele"},
        {name = "The Wavemender's Mantle", id = 32517, bias = "MS > OS"},
        {name = "Boneweave Girdle", id = 32346, bias = "Hunter > Enhance > Ret > DPS"},
        {name = "Crown of Empowered Fate", id = 32354, bias = "MS > OS"},
        {name = "Dreadboots of the Legion", id = 32345, bias = "DPS"},
        {name = "Translucent Spellthread Necklace", id = 32349, bias = "Warlock > Shadow"},
        {name = "Pendant of Titans", id = 32362, bias = "Prot >= Bear"},
        {name = "Touch of Inspiration", id = 32350, bias = "MS > OS"},
        {name = "Torch of the Damned", id = 32332, bias = "Ret > Arms"},
        {name = "Naaru-Blessed Life Rod", id = 32363, bias = "Holy"},
      },
    },
    {
      boss = "Teron Gorefiend",
      items = {
        {name = "Shadowmoon Destroyer's Drape", id = 32323, bias = "Rogue = Enhance > DPS > BM = Ret"},
        {name = "Cowl of Benevolence", id = 32329, bias = "Holy > Resto"},
        {name = "Robe of the Shadow Council", id = 32327, bias = "MS > OS"},
        {name = "Insidious Bands", id = 32324, bias = "Rogue > Hunter"},
        {name = "Botanist's Gloves of Growth", id = 32328, bias = "Resto > Resto"},
        {name = "Softstep Boots of Tracking", id = 32510, bias = "Enhance > BM"},
        {name = "Gauntlets of Enforcement", id = 32280, bias = "Prot"},
        {name = "Girdle of Lordaeron's Fallen", id = 32512, bias = "Holy"},
        {name = "Totem of Ancestral Guidance", id = 32330, bias = "Ele"},
        {name = "Soul Cleaver", id = 32348, bias = "MS > OS"},
        {name = "Twisted Blades of Zarak", id = 32326, bias = "DPS > Rogue"},
        {name = "Rifle of the Stoic Guardian", id = 32325, bias = "Prot"},
      },
    },
    {
      boss = "Mother Shahraz",
      items = {
        {name = "Leggings of Devastation", id = 32367, bias = "Shadow >= MS > OS"},
        {name = "Shadowmaster's Boots", id = 32366, bias = "Survival > Ret = BM > Rogue = Cat"},
        {name = "Heartshatter Breastplate", id = 32365, bias = "MS > OS"},
        {name = "Nadina's Pendant of Purity", id = 32370, bias = "Holy > Resto > Holy > Resto"},
        {name = "Tome of the Lightbringer", id = 32368, bias = "Prot"},
        {name = "Blade of Savagery", id = 32369, bias = "Rogue > Warrior > Hunter"},
        {name = "Pauldrons of the Forgotten Conqueror", id = 31101, bias = "Prot > Warlock > Holy > Holy > Shadow > Ret"},
        {name = "Pauldrons of the Forgotten Protector", id = 31103, bias = "Ele = Resto > Hunter > DPS > Enhance"},
        {name = "Pauldrons of the Forgotten Vanquisher", id = 31102, bias = "Bear > Rogue > Cat > Balance > Fire > Resto > Arcane"},
      },
    },
    {
      boss = "The Illidari Council",
      items = {
        {name = "Cloak of the Illidari Council", id = 32331, bias = "Mage = Balance = Ele > Warlock > Shadow"},
        {name = "Belt of Divine Guidance", id = 32519, bias = "Holy = Resto"},
        {name = "Veil of Turning Leaves", id = 32518, bias = "MS > OS"},
        {name = "Forest Prowler's Helm", id = 32376, bias = "BM = Ret > Enhance", note = "Second BiS while waiting for Cursed Vision"},
        {name = "Helm of the Illidari Shatterer", id = 32373, bias = "Fury > Arms > Ret"},
        {name = "Madness of the Betrayer", id = 32505, bias = "DPS > Hunter > Rogue = Feral"},
        {name = "Leggings of the Forgotten Conqueror", id = 31098, bias = "Prot > Warlock > Holy > Holy = Shadow > Ret"},
        {name = "Leggings of the Forgotten Protector", id = 31100, bias = "Resto > BM > Prot > DPS > Survival > Ele = Enhance"},
        {name = "Leggings of the Forgotten Vanquisher", id = 31099, bias = "Bear > Rogue > Mage > Balance > Resto"},
      },
    },
    {
      boss = "Illidan Stormrage",
      items = {
        {name = "Shroud of the Highborne", id = 32524, bias = "Resto > Holy > Resto > Holy"},
        {name = "Cowl of the Illidari High Lord", id = 32525, bias = "Fire"},
        {name = "Cursed Vision of Sargeras", id = 32235, bias = "Enhance > Hunter = Ret > Fury > Rogue > Arms"},
        {name = "Faceplate of the Impenetrable", id = 32521, bias = "Prot > Prot"},
        {name = "Stormrage Signet Ring", id = 32497, bias = "Rogue > Enhance > Hunter = DPS > Feral"},
        {name = "The Skull of Gul'dan", id = 32483, bias = "Warlock > Mage = Balance > Ele > Shadow"},
        {name = "Memento of Tyrande", id = 32496, bias = "Holy > Resto > Holy = Resto"},
        {name = "Shard of Azzinoth", id = 32471, bias = "MS > OS"},
        {name = "Crystal Spire of Karabor", id = 32500, bias = "Holy > Resto > Holy > Resto"},
        {name = "Zhar'doom, Greatstaff of the Devourer", id = 32374, bias = "Shadow > Balance = Ele > Warlock = Mage"},
        {name = "Bulwark of Azzinoth", id = 32375, bias = "LC"},
        {name = "Black Bow of the Betrayer", id = 32336, bias = "Survival > BM"},
        {name = "Chestguard of the Forgotten Conqueror", id = 31089, bias = "Prot > Holy > Holy > Shadow > Ret > Warlock", note = "Consider prio'ing Warlocks that don't have Vestments after Prot Pal."},
        {name = "Chestguard of the Forgotten Protector", id = 31091, bias = "Ele = Resto > Hunter > Warrior > Enhance"},
        {name = "Chestguard of the Forgotten Vanquisher", id = 31090, bias = "Bear > Rogue > Cat > Balance > Resto > Mage"},
        {name = "Warglaive of Azzinoth", id = 32837, bias = "LC", note = "Main-hand tooltip; off-hand item ID is 32838."},
      },
    },
    {
      boss = "Trash",
      items = {
        {name = "Shroud of the Final Stand", id = 34012, bias = "Holy > Resto"},
        {name = "Treads of the Den Mother", id = 32593, bias = "Bear"},
        {name = "Chestguard of Relentless Storms", id = 32592, bias = "MS > OS"},
        {name = "Pillager's Gauntlets", id = 32608, bias = "MS > OS"},
        {name = "Girdle of the Lightbearer", id = 32606, bias = "MS > OS"},
        {name = "Band of Devastation", id = 32526, bias = "Ret > DPS > Enhance"},
        {name = "Blessed Band of Karabor", id = 32528, bias = "Resto (113) > Holy > Resto > Resto > Holy", note = "Check Haste!"},
        {name = "Ring of Ancient Knowledge", id = 32527, bias = "Shadow (146) > Warlock = Ele = Balance > Mage > Shadow", note = "Check Haste!"},
        {name = "Swiftsteel Bludgeon", id = 32943, bias = "MS > OS"},
        {name = "Illidari Runeshield", id = 34011, bias = "Prot > Ele"},
      },
    },
    {
      boss = "Patterns",
      items = {
        {name = "Dawnsteel Bracers", id = 32571, bias = "MS > OS"},
        {name = "Dawnsteel Shoulders", id = 32573, bias = "MS > OS"},
        {name = "Swiftsteel Bracers", id = 32568, bias = "MS > OS"},
        {name = "Swiftsteel Shoulders", id = 32570, bias = "MS > OS"},
        {name = "Bindings of Lightning Reflexes", id = 32574, bias = "Ret > Enhance > Hunter > DPS"},
        {name = "Bracers of Renewed Life", id = 32582, bias = "Resto"},
        {name = "Living Earth Bindings", id = 32577, bias = "Resto"},
        {name = "Living Earth Shoulders", id = 32579, bias = "MS > OS"},
        {name = "Shoulders of Lightning Reflexes", id = 32575, bias = "MS > OS"},
        {name = "Shoulderpads of Renewed Life", id = 32583, bias = "Resto", note = "If LW"},
        {name = "Swiftstrike Bracers", id = 32580, bias = "MS > OS"},
        {name = "Swiftstrike Shoulders", id = 32581, bias = "Enhance > Ret > Hunter > DPS"},
        {name = "Bracers of Nimble Thought", id = 32586, bias = "Shadow > Destro = Ele > Balance > Arcane"},
        {name = "Mantle of Nimble Thought", id = 32587, bias = "Shadow > Destro > MS > OS", note = "BIS Shadow until T6 shoulders; BIS Warlock AOE Shoulders"},
        {name = "Swiftheal Mantle", id = 32585, bias = "Resto = Holy", note = "If Tailoring"},
        {name = "Swiftheal Wraps", id = 32584, bias = "Holy"},
      },
    },
  },
}
